# Generated by Django 4.2.7 on 2024-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dabeli", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
